# version: "3.3"
# services:
#   app:
#     build: 
#       context: .
#     command: npm start
#     depends_on:
#       - db
#     ports:
#       - "8888:8888"
#     environment:
#       NODE_ENV: development
#       DB_HOST: host.docker.internal
#     extra_hosts:
#       - "host.docker.internal:host-gateway"
#     networks:
#       - conn

#   db:
#     image: mysql:8.0
#     ports:
#       - "3307:3306"
#     environment:
#       MYSQL_DATABASE: users
#       MYSQL_ALLOW_EMPTY_PASSWORD: ok
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_USER: parth
#       MYSQL_PASSWORD: deq@123
#       MYSQL_ROOT_HOST: '%'
#     networks:
#       - conn
# networks:
#   conn:
#     driver: bridge


version: "3.3"
services:
  app:
    build: 
      context: .
    command: npm start
    depends_on:
      - db
    ports:
      - "8888:8888"
    environment:
      NODE_ENV: development
      DB_HOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - conn

  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      POSTGRES_PASSWORD: mysql
    networks:
      - conn
networks:
  conn:
    driver: bridge
